from __future__ import annotations
"""
Japanese INN → English INN bridge table.

These are the Japanese Katakana transliterations of INN drug names as used
in Japan MHLW 薬価基準, mapped to their WHO INN English equivalents.

Coverage: top ~280 drugs by prescription volume in Japan,
focusing on drugs also present in Taiwan's NHI reimbursement list.

Used by ppp.py to enable cross-country name matching between MHLW and NHI data.
"""
from typing import List, Tuple

# (japanese_generic_name, english_inn)
BRIDGE: List[Tuple[str, str]] = [
    # Cardiovascular
    ("アムロジピン", "amlodipine"),
    ("アムロジピンベシル酸塩", "amlodipine"),
    ("カンデサルタン", "candesartan"),
    ("カンデサルタン　シレキセチル", "candesartan cilexetil"),
    ("バルサルタン", "valsartan"),
    ("テルミサルタン", "telmisartan"),
    ("オルメサルタン", "olmesartan"),
    ("イルベサルタン", "irbesartan"),
    ("ロサルタン", "losartan"),
    ("ロサルタンカリウム", "losartan"),
    ("エナラプリル", "enalapril"),
    ("エナラプリルマレイン酸塩", "enalapril"),
    ("リシノプリル", "lisinopril"),
    ("ペリンドプリル", "perindopril"),
    ("ラミプリル", "ramipril"),
    ("アテノロール", "atenolol"),
    ("ビソプロロール", "bisoprolol"),
    ("ビソプロロールフマル酸塩", "bisoprolol"),
    ("カルベジロール", "carvedilol"),
    ("メトプロロール", "metoprolol"),
    ("ニフェジピン", "nifedipine"),
    ("ジルチアゼム", "diltiazem"),
    ("ジルチアゼム塩酸塩", "diltiazem"),
    ("ベラパミル", "verapamil"),
    ("ベラパミル塩酸塩", "verapamil"),
    ("ニカルジピン", "nicardipine"),
    ("フロセミド", "furosemide"),
    ("スピロノラクトン", "spironolactone"),
    ("ヒドロクロロチアジド", "hydrochlorothiazide"),
    ("インダパミド", "indapamide"),
    ("クロルタリドン", "chlortalidone"),
    ("ジゴキシン", "digoxin"),
    ("アミオダロン", "amiodarone"),
    ("アミオダロン塩酸塩", "amiodarone"),
    ("ワルファリン", "warfarin"),
    ("ワルファリンカリウム", "warfarin"),
    ("ダビガトラン", "dabigatran"),
    ("リバーロキサバン", "rivaroxaban"),
    ("アピキサバン", "apixaban"),
    ("エドキサバン", "edoxaban"),
    ("クロピドグレル", "clopidogrel"),
    ("クロピドグレル硫酸塩", "clopidogrel"),
    ("アスピリン", "aspirin"),
    ("チカグレロル", "ticagrelor"),
    ("プラスグレル", "prasugrel"),
    ("シロスタゾール", "cilostazol"),
    ("アトルバスタチン", "atorvastatin"),
    ("アトルバスタチンカルシウム", "atorvastatin"),
    ("ロスバスタチン", "rosuvastatin"),
    ("ロスバスタチンカルシウム", "rosuvastatin"),
    ("ピタバスタチン", "pitavastatin"),
    ("ピタバスタチンカルシウム", "pitavastatin"),
    ("プラバスタチン", "pravastatin"),
    ("プラバスタチンナトリウム", "pravastatin"),
    ("シンバスタチン", "simvastatin"),
    ("フルバスタチン", "fluvastatin"),
    ("エゼチミブ", "ezetimibe"),
    ("フェノフィブラート", "fenofibrate"),
    ("ベザフィブラート", "bezafibrate"),
    ("イコサペント酸エチル", "icosapent ethyl"),
    ("ニトログリセリン", "glyceryl trinitrate"),
    ("硝酸イソソルビド", "isosorbide dinitrate"),
    ("一硝酸イソソルビド", "isosorbide mononitrate"),
    # Diabetes
    ("メトホルミン", "metformin"),
    ("メトホルミン塩酸塩", "metformin"),
    ("グリメピリド", "glimepiride"),
    ("グリベンクラミド", "glibenclamide"),
    ("グリクラジド", "gliclazide"),
    ("ピオグリタゾン", "pioglitazone"),
    ("ピオグリタゾン塩酸塩", "pioglitazone"),
    ("シタグリプチン", "sitagliptin"),
    ("シタグリプチンリン酸塩水和物", "sitagliptin"),
    ("アログリプチン", "alogliptin"),
    ("アログリプチン安息香酸塩", "alogliptin"),
    ("ビルダグリプチン", "vildagliptin"),
    ("テネリグリプチン", "teneligliptin"),
    ("リナグリプチン", "linagliptin"),
    ("トレラグリプチン", "trelagliptin"),
    ("エンパグリフロジン", "empagliflozin"),
    ("ダパグリフロジン", "dapagliflozin"),
    ("カナグリフロジン", "canagliflozin"),
    ("ルセオグリフロジン", "luseogliflozin"),
    ("インスリン グラルギン", "insulin glargine"),
    ("インスリン デグルデク", "insulin degludec"),
    ("インスリン リスプロ", "insulin lispro"),
    ("インスリン アスパルト", "insulin aspart"),
    ("インスリン グルリジン", "insulin glulisine"),
    ("エキセナチド", "exenatide"),
    ("リラグルチド", "liraglutide"),
    ("セマグルチド", "semaglutide"),
    ("デュラグルチド", "dulaglutide"),
    # Respiratory
    ("サルブタモール", "salbutamol"),
    ("サルメテロール", "salmeterol"),
    ("フォルモテロール", "formoterol"),
    ("インダカテロール", "indacaterol"),
    ("チオトロピウム", "tiotropium"),
    ("チオトロピウム臭化物水和物", "tiotropium"),
    ("グリコピロニウム", "glycopyrronium"),
    ("ウメクリジニウム", "umeclidinium"),
    ("フルチカゾン", "fluticasone"),
    ("ブデソニド", "budesonide"),
    ("ベクロメタゾン", "beclometasone"),
    ("モメタゾン", "mometasone"),
    ("モンテルカスト", "montelukast"),
    ("モンテルカストナトリウム", "montelukast"),
    ("プランルカスト", "pranlukast"),
    ("セチリジン", "cetirizine"),
    ("セチリジン塩酸塩", "cetirizine"),
    ("フェキソフェナジン", "fexofenadine"),
    ("フェキソフェナジン塩酸塩", "fexofenadine"),
    ("ロラタジン", "loratadine"),
    ("デスロラタジン", "desloratadine"),
    ("ビラスチン", "bilastine"),
    ("レボセチリジン", "levocetirizine"),
    # Gastrointestinal
    ("オメプラゾール", "omeprazole"),
    ("ランソプラゾール", "lansoprazole"),
    ("ラベプラゾール", "rabeprazole"),
    ("ラベプラゾールナトリウム", "rabeprazole"),
    ("エソメプラゾール", "esomeprazole"),
    ("ボノプラザン", "vonoprazan"),
    ("ボノプラザンフマル酸塩", "vonoprazan"),
    ("ファモチジン", "famotidine"),
    ("ラニチジン", "ranitidine"),
    ("シメチジン", "cimetidine"),
    ("スクラルファート", "sucralfate"),
    ("ドンペリドン", "domperidone"),
    ("メトクロプラミド", "metoclopramide"),
    ("メトクロプラミド塩酸塩水和物", "metoclopramide"),
    ("モサプリド", "mosapride"),
    ("モサプリドクエン酸塩水和物", "mosapride"),
    ("イリノテカン", "irinotecan"),
    ("センノシド", "sennosides"),
    ("ピコスルファート", "sodium picosulfate"),
    ("酸化マグネシウム", "magnesium oxide"),
    ("ブチルスコポラミン", "butylscopolamine"),
    # CNS / Psychiatry
    ("アセタミノフェン", "paracetamol"),
    ("パラセタモール", "paracetamol"),
    ("イブプロフェン", "ibuprofen"),
    ("ロキソプロフェン", "loxoprofen"),
    ("ロキソプロフェンナトリウム水和物", "loxoprofen"),
    ("ジクロフェナク", "diclofenac"),
    ("ジクロフェナクナトリウム", "diclofenac"),
    ("インドメタシン", "indometacin"),
    ("メロキシカム", "meloxicam"),
    ("セレコキシブ", "celecoxib"),
    ("エトドラク", "etodolac"),
    ("プレガバリン", "pregabalin"),
    ("ガバペンチン", "gabapentin"),
    ("アミトリプチリン", "amitriptyline"),
    ("アミトリプチリン塩酸塩", "amitriptyline"),
    ("ミルタザピン", "mirtazapine"),
    ("パロキセチン", "paroxetine"),
    ("パロキセチン塩酸塩水和物", "paroxetine"),
    ("セルトラリン", "sertraline"),
    ("セルトラリン塩酸塩", "sertraline"),
    ("エスシタロプラム", "escitalopram"),
    ("エスシタロプラムシュウ酸塩", "escitalopram"),
    ("フルボキサミン", "fluvoxamine"),
    ("フルボキサミンマレイン酸塩", "fluvoxamine"),
    ("デュロキセチン", "duloxetine"),
    ("デュロキセチン塩酸塩", "duloxetine"),
    ("ベンラファキシン", "venlafaxine"),
    ("ブプロピオン", "bupropion"),
    ("ハロペリドール", "haloperidol"),
    ("リスペリドン", "risperidone"),
    ("オランザピン", "olanzapine"),
    ("クエチアピン", "quetiapine"),
    ("クエチアピンフマル酸塩", "quetiapine"),
    ("アリピプラゾール", "aripiprazole"),
    ("ブレクスピプラゾール", "brexpiprazole"),
    ("パリペリドン", "paliperidone"),
    ("クロザピン", "clozapine"),
    ("ゾテピン", "zotepine"),
    ("アセナピン", "asenapine"),
    ("ルラシドン", "lurasidone"),
    ("ルラシドン塩酸塩", "lurasidone"),
    ("リチウム", "lithium"),
    ("炭酸リチウム", "lithium carbonate"),
    ("バルプロ酸", "valproic acid"),
    ("バルプロ酸ナトリウム", "valproate sodium"),
    ("ラモトリギン", "lamotrigine"),
    ("カルバマゼピン", "carbamazepine"),
    ("オクスカルバゼピン", "oxcarbazepine"),
    ("レベチラセタム", "levetiracetam"),
    ("トピラマート", "topiramate"),
    ("クロナゼパム", "clonazepam"),
    ("ジアゼパム", "diazepam"),
    ("アルプラゾラム", "alprazolam"),
    ("ロラゼパム", "lorazepam"),
    ("エスタゾラム", "estazolam"),
    ("トリアゾラム", "triazolam"),
    ("ゾルピデム", "zolpidem"),
    ("ゾルピデム酒石酸塩", "zolpidem"),
    ("スボレキサント", "suvorexant"),
    ("レンボレキサント", "lemborexant"),
    ("ドネペジル", "donepezil"),
    ("ドネペジル塩酸塩", "donepezil"),
    ("ガランタミン", "galantamine"),
    ("ガランタミン臭化水素酸塩", "galantamine"),
    ("メマンチン", "memantine"),
    ("メマンチン塩酸塩", "memantine"),
    ("リバスチグミン", "rivastigmine"),
    ("レボドパ", "levodopa"),
    ("エンタカポン", "entacapone"),
    ("プラミペキソール", "pramipexole"),
    ("ロピニロール", "ropinirole"),
    ("ロチゴチン", "rotigotine"),
    ("アマンタジン", "amantadine"),
    ("アマンタジン塩酸塩", "amantadine"),
    # Antibiotics / Antivirals
    ("アモキシシリン", "amoxicillin"),
    ("アモキシシリン水和物", "amoxicillin"),
    ("クラブラン酸", "clavulanic acid"),
    ("アンピシリン", "ampicillin"),
    ("セファレキシン", "cefalexin"),
    ("セフジニル", "cefdinir"),
    ("セフカペン", "cefcapene"),
    ("セフトリアキソン", "ceftriaxone"),
    ("セフォタキシム", "cefotaxime"),
    ("セフォペラゾン", "cefoperazone"),
    ("クラリスロマイシン", "clarithromycin"),
    ("アジスロマイシン", "azithromycin"),
    ("アジスロマイシン水和物", "azithromycin"),
    ("エリスロマイシン", "erythromycin"),
    ("レボフロキサシン", "levofloxacin"),
    ("レボフロキサシン水和物", "levofloxacin"),
    ("シプロフロキサシン", "ciprofloxacin"),
    ("シプロフロキサシン塩酸塩水和物", "ciprofloxacin"),
    ("ミノサイクリン", "minocycline"),
    ("ミノサイクリン塩酸塩", "minocycline"),
    ("ドキシサイクリン", "doxycycline"),
    ("メトロニダゾール", "metronidazole"),
    ("スルファメトキサゾール", "sulfamethoxazole"),
    ("トリメトプリム", "trimethoprim"),
    ("バンコマイシン", "vancomycin"),
    ("バンコマイシン塩酸塩", "vancomycin"),
    ("テイコプラニン", "teicoplanin"),
    ("リネゾリド", "linezolid"),
    ("メロペネム", "meropenem"),
    ("メロペネム水和物", "meropenem"),
    ("イミペネム", "imipenem"),
    ("アシクロビル", "aciclovir"),
    ("バラシクロビル", "valaciclovir"),
    ("バラシクロビル塩酸塩", "valaciclovir"),
    ("ガンシクロビル", "ganciclovir"),
    ("オセルタミビル", "oseltamivir"),
    ("オセルタミビルリン酸塩", "oseltamivir"),
    ("バロキサビル", "baloxavir"),
    ("テノホビル", "tenofovir"),
    ("エムトリシタビン", "emtricitabine"),
    ("ラミブジン", "lamivudine"),
    ("アバカビル", "abacavir"),
    ("ドルテグラビル", "dolutegravir"),
    ("ビクテグラビル", "bictegravir"),
    ("ソホスブビル", "sofosbuvir"),
    ("レジパスビル", "ledipasvir"),
    # Oncology
    ("タモキシフェン", "tamoxifen"),
    ("タモキシフェンクエン酸塩", "tamoxifen"),
    ("レトロゾール", "letrozole"),
    ("アナストロゾール", "anastrozole"),
    ("エキセメスタン", "exemestane"),
    ("イマチニブ", "imatinib"),
    ("イマチニブメシル酸塩", "imatinib"),
    ("ゲフィチニブ", "gefitinib"),
    ("エルロチニブ", "erlotinib"),
    ("エルロチニブ塩酸塩", "erlotinib"),
    ("オシメルチニブ", "osimertinib"),
    ("ベバシズマブ", "bevacizumab"),
    ("トラスツズマブ", "trastuzumab"),
    ("リツキシマブ", "rituximab"),
    ("ニボルマブ", "nivolumab"),
    ("ペムブロリズマブ", "pembrolizumab"),
    ("ボルテゾミブ", "bortezomib"),
    ("レナリドミド", "lenalidomide"),
    ("スニチニブ", "sunitinib"),
    ("スニチニブリンゴ酸塩", "sunitinib"),
    ("ソラフェニブ", "sorafenib"),
    ("カペシタビン", "capecitabine"),
    ("オキサリプラチン", "oxaliplatin"),
    ("シスプラチン", "cisplatin"),
    ("カルボプラチン", "carboplatin"),
    ("パクリタキセル", "paclitaxel"),
    ("ドセタキセル", "docetaxel"),
    ("ドセタキセル水和物", "docetaxel"),
    ("ゲムシタビン", "gemcitabine"),
    ("ゲムシタビン塩酸塩", "gemcitabine"),
    ("エトポシド", "etoposide"),
    ("メトトレキサート", "methotrexate"),
    # Immunology / Biologics
    ("プレドニゾロン", "prednisolone"),
    ("デキサメタゾン", "dexamethasone"),
    ("ヒドロコルチゾン", "hydrocortisone"),
    ("メチルプレドニゾロン", "methylprednisolone"),
    ("シクロスポリン", "ciclosporin"),
    ("タクロリムス", "tacrolimus"),
    ("タクロリムス水和物", "tacrolimus"),
    ("ミコフェノール酸モフェチル", "mycophenolate mofetil"),
    ("アザチオプリン", "azathioprine"),
    ("メサラジン", "mesalazine"),
    ("インフリキシマブ", "infliximab"),
    ("アダリムマブ", "adalimumab"),
    ("エタネルセプト", "etanercept"),
    ("セクキヌマブ", "secukinumab"),
    ("ウステキヌマブ", "ustekinumab"),
    ("トシリズマブ", "tocilizumab"),
    ("アバタセプト", "abatacept"),
    # Endocrinology
    ("レボチロキシン", "levothyroxine"),
    ("レボチロキシンナトリウム水和物", "levothyroxine"),
    ("アレンドロン酸", "alendronic acid"),
    ("アレンドロン酸ナトリウム水和物", "alendronic acid"),
    ("リセドロン酸", "risedronic acid"),
    ("リセドロン酸ナトリウム水和物", "risedronic acid"),
    ("ラロキシフェン", "raloxifene"),
    ("ラロキシフェン塩酸塩", "raloxifene"),
    ("カルシトリオール", "calcitriol"),
    ("アルファカルシドール", "alfacalcidol"),
    ("テストステロン", "testosterone"),
    # Pain / Anaesthesia
    ("モルヒネ", "morphine"),
    ("オキシコドン", "oxycodone"),
    ("オキシコドン塩酸塩水和物", "oxycodone"),
    ("フェンタニル", "fentanyl"),
    ("トラマドール", "tramadol"),
    ("トラマドール塩酸塩", "tramadol"),
    ("タペンタドール", "tapentadol"),
    ("ブプレノルフィン", "buprenorphine"),
    ("ナルトレキソン", "naltrexone"),
    ("ナロキソン", "naloxone"),
    ("プロポフォール", "propofol"),
    ("ミダゾラム", "midazolam"),
    ("ケタミン", "ketamine"),
    ("ケタミン塩酸塩", "ketamine"),
    ("リドカイン", "lidocaine"),
    ("リドカイン塩酸塩", "lidocaine"),
    # Ophthalmology
    ("ラタノプロスト", "latanoprost"),
    ("トラボプロスト", "travoprost"),
    ("ビマトプロスト", "bimatoprost"),
    ("チモロール", "timolol"),
    ("チモロールマレイン酸塩", "timolol"),
    ("ドルゾラミド", "dorzolamide"),
    ("ドルゾラミド塩酸塩", "dorzolamide"),
    ("ランタニン", "ranibizumab"),
    ("ラニビズマブ", "ranibizumab"),
    ("アフリベルセプト", "aflibercept"),
    # Urology
    ("タムスロシン", "tamsulosin"),
    ("タムスロシン塩酸塩", "tamsulosin"),
    ("シロドシン", "silodosin"),
    ("ナフトピジル", "naftopidil"),
    ("フィナステリド", "finasteride"),
    ("デュタステリド", "dutasteride"),
    ("シルデナフィル", "sildenafil"),
    ("シルデナフィルクエン酸塩", "sildenafil"),
    ("タダラフィル", "tadalafil"),
    ("バルデナフィル", "vardenafil"),
    ("バルデナフィル塩酸塩水和物", "vardenafil"),
    ("ソリフェナシン", "solifenacin"),
    ("ソリフェナシンコハク酸塩", "solifenacin"),
    ("トルテロジン", "tolterodine"),
    ("ミラベグロン", "mirabegron"),
    # Haematology / Iron
    ("エリスロポエチン", "epoetin"),
    ("エポエチン", "epoetin"),
    ("フェリチン", "ferritin"),
    ("硫酸鉄", "ferrous sulfate"),
    ("ヘパリン", "heparin"),
    ("エノキサパリン", "enoxaparin"),
    ("エノキサパリンナトリウム", "enoxaparin"),
    ("フォンダパリヌクス", "fondaparinux"),
    ("フォンダパリヌクスナトリウム", "fondaparinux"),
]


def build_index() -> Tuple[dict, dict]:
    """
    Return (exact_map, token_map) for fast lookup.
    exact_map: normalised full JP name → EN INN
    token_map: first significant token of JP name → EN INN
    """
    import re

    def norm(s: str) -> str:
        return s.strip().lower()

    def first_token(s: str) -> str:
        # For Japanese, take up to the first 6 kana chars as a key
        # For romaji, take the first word
        m = re.match(r"[a-z0-9]+", s.lower())
        if m:
            return m.group(0)
        # For Japanese kana/kanji, use first 5 characters
        stripped = re.sub(r"[\s　・（）()0-9０-９]", "", s)
        return stripped[:5] if len(stripped) >= 5 else stripped

    exact: dict[str, str] = {}
    token: dict[str, str] = {}

    for jp, en in BRIDGE:
        k = norm(jp)
        exact[k] = en
        tok = first_token(k)
        if len(tok) >= 3:
            token.setdefault(tok, en)   # first entry wins

    return exact, token
